name: QuickWarp
version: 1.0
author: S-mallow
main: me.smallow.quickwarp.QuickWarp
api-version: 1.19

commands:
  quickwarp:
    description: "QuickWarp management command"
    usage: /<command>
    aliases:
      - qw

permissions:
  quickwarp.*:
    default: op
    description: Give players with op everything by default
  quickwarp.use:
    default: true
    description: Allows to use QuickWarp
  quickwarp.add:
    default: op
    description: Allows to add QuickWarp locations
  quickwarp.remove:
    default: op
    description: Allows to remove QuickWarp locations
  quickwarp.rename:
    default: op
    description: Allows to update QuickWarp names
  quickwarp.relocate:
    default: op
    description: Allows to update QuickWarp locations
  quickwarp.setitem:
    default: op
    description: Allows to update QuickWarp items